trigger: none

schedules:
- cron: "30 18 * * *"
  displayName: Ejecutar diariamente 15:30 ARG
  branches:
    include:
    - main
  always: true

stages:

- stage: ActualizaCarpetaRelease
  displayName: 01 - Actualizar carpetas Release
  jobs:
  - job: ActualizarRelease_QA01
    displayName: Actualizar Setup SAR y OFISIS en QA-01
    pool:
      name: Softland-QA
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.Name -equals Softland-QA-01
    steps:
    - template: ActualizaCarpetaRelease.YAML

  - job: ActualizarRelease_QA02
    displayName: Actualizar Setup SAR y OFISIS en QA-02
    pool:
      name: Softland-QA
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.Name -equals Softland-QA-02
    steps:
    - template: ActualizaCarpetaRelease.YAML

- stage: EjecutaSetup
  displayName: 02 - Ejecutar Setup
  dependsOn: ActualizaCarpetaRelease
  condition: succeeded()
  jobs:
  - job: InstalarSetup_QA01
    displayName: Ejecutar Setup Softland en QA-01
    pool:
      name: Softland-QA
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.Name -equals Softland-QA-01
    timeoutInMinutes: 90
    steps:
    - template: ejecuta.YAML

  - job: InstalarSetup_QA02
    displayName: Ejecutar Setup Softland en QA-02
    pool:
      name: Softland-QA
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.Name -equals Softland-QA-02
    timeoutInMinutes: 90
    steps:
    - template: ejecuta.YAML
